const teamNameAbbreviations = {
  Liverpool: "LIV",
  Arsenal: "ARS",
  "Nottingham Forest": "NFO",
  Chelsea: "CHE",
  "Manchester City": "MCI",
  Newcastle: "NEW",
  Bournemouth: "BOU",
  "Aston Villa": "AVL",
  Brighton: "BRI",
  Fulham: "FUL",
  Brentford: "BRE",
  "Crystal Palace": "CRY",
  "Manchester United": "MUN",
  "West Ham": "WHU",
  Tottenham: "TOT",
  Everton: "EVE",
  Wolves: "WOL",
  Ipswich: "IPS",
  Leicester: "LEI",
  Southampton: "SOU",
  "Bayer Leverkusen": "LEV",
  "Bayern München": "FCB",
  "Borussia Dortmund": "BVB",
  "Borussia Mönchengladbach": "BMG",
  "Eintracht Frankfurt": "SGE",
  "FC Augsburg": "FCA",
  "SC Freiburg": "SCF",
  "1. FC Heidenheim": "HDH",
  "1899 Hoffenheim": "TSG",
  "Holstein Kiel": "KSV",
  "FSV Mainz 05": "M05",
  "RB Leipzig": "RBL",
  "FC St. Pauli": "STP",
  "Union Berlin": "FCU",
  "VfB Stuttgart": "VFB",
  "VfL Bochum": "BOC",
  "VfL Wolfsburg": "WOB",
  "Werder Bremen": "SVW",
  Angers: "SCO",
  Auxerre: "AJA",
  "Stade Brestois 29": "BRE",
  "LE Havre": "HAC",
  Lille: "LIL",
  Monaco: "ASM",
  Montpellier: "MON",
  Nantes: "NAN",
  Nice: "NIC",
  Lyon: "OL",
  Marseille: "OM",
  "Paris Saint Germain": "PSG",
  Lens: "RCL",
  Reims: "SR",
  Rennes: "REN",
  "Saint Etienne": "ASS",
  Strasbourg: "STR",
  Toulouse: "TFC",
  "AC Milan": "MIL",
  "AS Roma": "ROM",
  Atalanta: "ATA",
  Bologna: "BOL",
  Cagliari: "CAG",
  Como: "COM",
  Empoli: "EMP",
  Fiorentina: "FIO",
  Genoa: "GEN",
  Verona: "VER",
  Inter: "INT",
  Juventus: "JUV",
  Lazio: "LAZ",
  Lecce: "LEC",
  Monza: "MON",
  Napoli: "NAP",
  Parma: "PAR",
  Torino: "TOR",
  Udinese: "UDI",
  Venezia: "VEN",
  Alaves: "ALA",
  "Athletic Club": "ATH",
  "Atletico Madrid": "ATM",
  Barcelona: "BAR",
  "Celta Vigo": "CEL",
  Espanyol: "ESP",
  Getafe: "GET",
  Girona: "GIR",
  "Las Palmas": "LPM",
  Leganes: "LEG",
  Osasuna: "OSA",
  "Rayo Vallecano": "RAY",
  Mallorca: "MLL",
  "Real Betis": "BET",
  "Real Madrid": "RMA",
  "Real Sociedad": "RSO",
  Sevilla: "SEV",
  Valencia: "VAL",
  Valladolid: "VLD",
  Villarreal: "VIL",
};

export function teamNameAbbreviation(name: string) {
  return teamNameAbbreviations[name as keyof typeof teamNameAbbreviations];
}
